### ISSUE TITLE
See stderr

### ISSUE THREAD

**Issue by armetiz** [TheBigBrainsCompany/capistrano-symfony#1]
``` bash
bundle exec cap development symfony:run['doctrine:schema:validate','--env=prod']
```

I want to see something like that :

``` bash
# [Mapping]  OK - The mapping files are correct.
# [Database] FAIL - The database schema is not in sync with the current mapping file.
```

**Comment by borisguery** [comment]
Afaik, it is correct behavior, I don't remember how symfony console plays with stdout & stderr, but capistrano will be verbose depending on the current log level which can be set using `logger.level = Logger::MAX_LEVEL` or by using the command line option `--log-level`
