### ISSUE TITLE
Linked_files and upload parameters

### ISSUE THREAD

**Issue by armetiz** [TheBigBrainsCompany/capistrano-symfony#11]
The [:deploy:check:linked_files](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/tasks/deploy.rake#L73) fails is parameters.yml file does not exists.

Our upload parameters task is executed far away after this check..

So, what do you think to move this hook before "deploy:check" ?

cc @borisguery

**Comment by benjamindulau** [comment]
:+1: Just initialized a new project deployment configuration and this is annoying ;-)

**Comment by cyb3rd4d** [comment]
Hi

The task parameters:upload has this statement at line 46 in the symfony.rake:

``` ruby
within release_path do
```

But the release path exists if a deployment is performed at least once.
I suggest to replace by:

``` ruby
within shared_path do
```

This will allow to chain these tasks for the first deployment:
cap production deploy:check:linked_dirs
cap production symfony:parameters:upload
cap production deploy

**Comment by greg0ire** [comment]
:+1:

**Comment by armetiz** [comment]
Thanks to this PR : https://github.com/TheBigBrainsCompany/capistrano-symfony/pull/13
