### ISSUE TITLE
Gem naming conflict

### ISSUE THREAD

**Issue by sandermarechal** [TheBigBrainsCompany/capistrano-symfony#12]
There is a naming conflict with this gem now that the Capistrano developers also provide a Symfony gem: https://github.com/capistrano/symfony

Would you consider renaming this gem so that the capistrano-symfony name can be used by the Capistrano developers?

**Comment by armetiz** [comment]
See [capistrano/symfony#25](https://github.com/capistrano/symfony/issues/25)
