### ISSUE TITLE
Should we require composer gem?

### ISSUE THREAD

**Issue by borisguery** [TheBigBrainsCompany/capistrano-symfony#5]
Symfony2 is tightly tied to composer, however, when using this gem we actually need to use the composer gem to ensure a working installation.

What about wrapping the composer gem to have a fully working symfony2 deployment?

**Comment by armetiz** [comment]
I guess you right, It could be a pleasure to see a PR with this dependency :p

**Comment by armetiz** [comment]
Done : https://github.com/TheBigBrainsCompany/capistrano-symfony/commit/e9baa365f1b6f0e2fe06c278758a88b863315710
