### ISSUE TITLE
Handle parameters.yml

### ISSUE THREAD

**Issue by borisguery** [TheBigBrainsCompany/capistrano-symfony#6]
Currently, we need to manually deploy the `parameters.yml`, in case where a parameter is added it can make the deployment fail. It may not be desired.

We should find a way to automatically deploy new parameters, while allowing to keep privacy of credentials, etc.

Any thoughts?

**Comment by borisguery** [comment]
ok, so I pondered a bit this thing, and I was thinking of a capistrano parameter like: `handle_parameters`  which could check for any change between remote `parameters.yml` and local  configuration and ask to upload the newly changed file.

This will let developers which doesn't have permissions nor remote credentials don't matter about it, while making sure for others that their new parameters are properly deployed.

what do you think?

**Comment by armetiz** [comment]
I totally agree that `parameters.yml` management is a shame. But I don't know how to handle upload easily and user-friendly.

**Comment by borisguery** [comment]
I'll work on that, I already wrote some working prototypes.

**Comment by armetiz** [comment]
Just a proposition :
- If a capistrano/files/parameters.{stage}.yml is defined, upload this file
- If not, upload the app/config/parameters.yml.dist

This is not the perfect solution, but it will even if the user doesn't define a dedicated parameters file.

**Comment by borisguery** [comment]
As previously discussed on IRC that's pretty much what I do.

The problem with this rule is that all deployers need to manage their own `parameters.yml` because it would get uploaded each time. But we don't want credentials and other sensible parameters to be shared across the repository.

Uploading the parameters only once has also problem because if we need to update it we have to do it manually.

So I can think of some rules like:
- If no parameters.yml on the remote ask the deployer if he's willing to upload it
- If an existing parameters.yml exists on the remote and locally and has the same hash than the local, do nothing
- If an existing parameters.yml exists on the remote and locally but the hash is different, ask the user
- If an existing parameters.yml exists on the remote but does not exist locally, do nothing

This way depending on the use cases people can agree on the best solution (manually sharing of the parameters) or let one granted user to manage the parameters while not bothering others.

Any thoughts?

**Comment by armetiz** [comment]
I think it's a really good solution,
I totally agree with you.

**Comment by armetiz** [comment]
https://github.com/TheBigBrainsCompany/capistrano-symfony/pull/10
