### ISSUE TITLE
Remove app.php

### ISSUE THREAD

**Issue by armetiz** [TheBigBrainsCompany/capistrano-symfony#9]
The app:clean_environment remove app_dev.php but also app.php due to **app*.php**.

**Comment by borisguery** [comment]
To be honest that was the expected behavior.
I find it inconsistent to have an `app.php` I'd rather use `app_prod.php` to explicitly set it as prod environment.

It should have been documented though.

**Comment by armetiz** [comment]
I understand and I agree with you, but It's not a standard Symfony feature.
